version: '3.9'

services:
  db:
    container_name: mydb
    image: mysql:5.7.10
    environment:
      - MYSQL_DATABASE=admin_app
      - MYSQL_USER=khaledallam
      - MYSQL_PASSWORD=Khaled@505
      - MYSQL_ROOT_PASSWORD=Khaled@505
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app
  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - app
  frontend:
    image: antoniopapa1991/admin-frontend
    ports:
      - 8001:80
    networks:
      - app
    depends_on:
      - backend
networks:
  app:
volumes:
  db-data:
