version: '3.9'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=backend
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - app
  frontend:
    container_name: frontend
    image: antoniopapa1991/admin-frontend
    ports:
      - 8001:80
    networks:
      - app
    depends_on:
      - backend
networks:
  app:
volumes:
  db-data:
